### Bienvenida
GET http://localhost:3000/

### Bienvenida
GET http://localhost:3000/apicontenido/



################################
##  GENEROS
################################

### Get de todos los generos
GET http://localhost:3000/apicontenido/generos

### Get generos por Id
GET http://localhost:3000/apicontenido/generos/24


### Crear un genero
POST http://localhost:3000/apicontenido/generos
Content-Type: application/json

{
  "nombre": "comi-tragico"
}

### Get generos por Id
GET http://localhost:3000/apicontenido/generos/23

### Get generos por Id
GET http://localhost:3000/apicontenido/generos/25

### Actualizar un genero totalmente 
PUT http://localhost:3000/apicontenido/generos/25
Content-Type: application/json

{
  "nombre": "comi-tragico-griego"
}

### Delete generos por Id
DELETE http://localhost:3000/apicontenido/generos/25





################################
##  CONTENIDO
################################

### Get de todos los contenidos
GET http://localhost:3000/apicontenido/contenido

### Get contenido por Id
GET http://localhost:3000/apicontenido/contenido/98

### Get contenido por Id y relaciones full
GET http://localhost:3000/apicontenido/contenido/98/full



### Delete contenido por Id
DELETE http://localhost:3000/apicontenido/contenido/101


### Crear un contenido
POST http://localhost:3000/apicontenido/contenido/
Content-Type: application/json

{
  "id": 101,
  "poster": "./posters/101.jpg",
  "titulo": "101 dalmatas",
  "categoria_id": "Película",
  "genero": [2, 12, 13, "Dálmatas"],
  "busqueda": [3, 89, 99, 1124, 1125, 1126, 1127, 1128, "101 dálmatas"],
  "resumen": "El delirante y gótico estilo de vida de la peculiar familia Addams se ve amenazado peligrosamente cuando el codicioso dúo que forman madre e hijo, con la ayuda de un abogado sin ningún escrúpulos, conspiran para hacerse con la fortuna familiar... (No se pierdan las locutras de Gomez, Morticia, Tío Lucas, Merlina, El tío Cosas, Dedos y Largo)",
  "temporadas": 0,
  "duracion": 101,
  "reparto": [826, 827, 828, 829, 830, 831, 832, 833, 834],
  "trailer": "https://www.youtube.com/embed/G388UMkJIBE"
}   

### Actualizar un contenidos totalmente 
PUT http://localhost:3000/apicontenido/101
Content-Type: application/json

{
  "titulo": "3022x2"
}

### Actualizar un contenidos parcialmente
PATCH http://localhost:3000/apicontenido/101
Content-Type: application/json

{
  "titulo": "3022x2"
}

### Actualizar un contenidos parcialmente con datos vacios
PATCH http://localhost:3000/apicontenido/101
Content-Type: application/json

{
  "titulo": ""
}


### DELETE Contenido por Id
DELETE http://localhost:3000/apicontenido/101










################################
##  CATEGORIAS
################################


### Get de todos las categorias
GET http://localhost:3000/apicontenido/categorias

### Get categorias por Id
GET http://localhost:3000/apicontenido/categorias/2

### Crear una categorias
POST http://localhost:3000/apicontenido/categorias
Content-Type: application/json

{
  "nombre": "Documental"
}

### Actualizar una categorias totalmente 
PUT http://localhost:3000/apicontenido/categorias/3
Content-Type: application/json

{
  "nombre": "Documental-serie-galaxia"
}

### Actualizar una categorias parcialmente
PATCH http://localhost:3000/apicontenido/categorias/3
Content-Type: application/json

{
  "nombre": "Documental-serie-galaxia2"
}

### Actualizar una categorias parcialmente con datos invalidos
PATCH http://localhost:3000/apicontenido/categorias/3
Content-Type: application/json

{
  "nombres": "ssss"
}

### Actualizar una categorias parcialmente con datos vacios
PATCH http://localhost:3000/apicontenido/categorias/3
Content-Type: application/json

{
  "nombre": ""
}

### DELETE categorias por Id
DELETE http://localhost:3000/apicontenido/categorias/3







################################
##  ACTORES
################################

### Get de todos los actores
GET http://localhost:3000/apicontenido/actores

### Get actor por Id
GET http://localhost:3000/apicontenido/actores/30

### Get actor por Id y sus contenidos
GET http://localhost:3000/apicontenido/actores/30/contenido 


### Crear un actor
POST http://localhost:3000/apicontenido/actores
Content-Type: application/json

{
  "nombre": "Gustavo Torrente"
}

### Actualizar un actor totalmente 
PUT http://localhost:3000/apicontenido/actores/840
Content-Type: application/json

{
  "nombre": "Gustavo Torrente Nuñez"
}

### Actualizar un actor parcialmente
PATCH http://localhost:3000/apicontenido/actores/840
Content-Type: application/json

{
  "nombre": "Gustavo Torrente Nuñez Quijada"
}

### Actualizar un actor parcialmente con datos invalidos
PATCH http://localhost:3000/apicontenido/actores/840
Content-Type: application/json

{
  "nombres": "ssss"
}

### Actualizar un actor parcialmente con datos vacios
PATCH http://localhost:3000/apicontenido/actores/840
Content-Type: application/json

{
  "nombre": ""
}


################################
##  GENEROS
################################

### Get de todos los generos
GET http://localhost:3000/apicontenido/generos

### Get genero por Id
GET http://localhost:3000/apicontenido/generos/20


### Get genero por Id y sus contenidos
GET http://localhost:3000/apicontenido/generos/30/contenido 


### Crear un genero
POST http://localhost:3000/apicontenido/generos
Content-Type: application/json

{
  "nombre": "Tragedia"
}

### Actualizar un genero totalmente 
PUT http://localhost:3000/apicontenido/generos/20
Content-Type: application/json

{
  "nombre": "Tragedia Griega"
}

### Actualizar un genero parcialmente
PATCH http://localhost:3000/apicontenido/generos/20
Content-Type: application/json

{
  "nombre": "Tragedia Griega"
}

### Actualizar un genero parcialmente con datos vacios
PATCH http://localhost:3000/apicontenido/generos/840
Content-Type: application/json

{
  "nombre": ""
}
