#Servidores 
@baseUrl = http://localhost:3000/apicontenido
#@baseUrl = https://relacional-backend-untref-production.up.railway.app/apicontenido


### Bienvenida
GET http://localhost:3000/

### Bienvenida
#GET https://relacional-backend-untref-production.up.railway.app/apicontenido/
GET {{baseUrl}}/

################################
##  CONTENIDO
################################


### Get contenido por Id con array numérico en relaciones
GET {{baseUrl}}/contenido/74

### Get contenido por Id y relaciones full
GET {{baseUrl}}/contenido/74/full


### Get contenidos por Id de actor
# Todas la obras de un actor en particular
GET {{baseUrl}}/contenido/actor/109

### Get contenidos por Id de actor
# Actor inexistente
GET {{baseUrl}}/contenido/actor/1099


### Get de todos los contenidos. Sin discriminar!
GET {{baseUrl}}/contenido


### Get de todos los contenidos, y opcinal consulta por:
  # Categoría: 1 (Id de la categoría en la base de datos: 1=Serie / 2=Película) 
  # Genero: Sci-Fi
  # Reparto: Pedro Pascal
  # Búsqueda: Suspenso
### Valores de los parámetros
@categoria = 1
@genero = Sci-Fi
@reparto = Pedro Pascal
@busqueda = Suspenso
### Obtener contenidos filtrados por parámetros específicos
GET {{baseUrl}}/contenido?categoria={{categoria}}&genero={{genero}}&reparto={{reparto}}&busqueda={{busqueda}}


### Valores de los parámetros. Solo genero
@genero = Sci-Fi
### Obtener contenidos filtrados por parámetros específicos
GET {{baseUrl}}/contenido?genero={{genero}}


##
#  No llegué con las busquedas parciales como por ejemplo:
#   >  @reparto = Pedro 
#  y que encuentre todos los Pedro, incluido "Pedro Pascal"
##



### Crear un contenido.
# En este caso, ya eiste y da: HTTP/1.1 409 Conflict
POST {{baseUrl}}/contenido/
Content-Type: application/json

  {
    "id": 17,
    "poster": "./posters/17.jpg",
    "titulo": "Halt and Catch Fire",
    "categoria_id": "Serie",
    "genero": [
      "Ficción",
      "Drama",
      "Tecnología"
    ],
    "busqueda": [
      "Halt and Catch Fire",
      "Ficción",
      "Drama",
      "Tecnología",
      "Lee Pace",
      "Scoot McNairy",
      "Mackenzie Davis",
      "Kerry Bishé",
      "Toby Huss",
      "Alana Cavanaugh"
    ],
    "resumen": "Situada en los inicios de la década de 1980, un visionario ficticio, un ingeniero electrónico y una prodigiosa ingeniera, se alían a una programadora de software para confrontar con las corporaciones informáticas dominantes de la época. El Personal de la firma y sus socios de negocio, comenzarán una carrera que cambiará la cultura en el Estado de Texas, cuna de las empresas de tecnología, casi de la misma forma que lo es hoy Silicon Valey. \n Esta historia ficticia emula el trabajo realizado, en su momento, por la firma Compaq, cuando clonó el BIOS de las Computadoras Personales IBM, dando vida así al económico mercado de los clones. Mostrando también, a lo largo de sus 4 temporadas, el nacimiento de la arquitectura abierta de hardware, los videojuegos online, las salas de chat y de trueque de productos físicos, los BBS, y las primeras nubes computacionales, hasta la llegada de Internet (sin dejar afuera la guerra de los web browsers).",
    "temporadas": 4,
    "reparto": [
      "Lee Pace",
      "Scoot McNairy",
      "Mackenzie Davis",
      "Kerry Bishé",
      "Toby Huss",
      "Alana Cavanaugh"
    ],
    "trailer": "https://www.youtube.com/embed/pWrioRji60A",
    "duracion": 0
  }

# Crear un contenido.
# No acepta parámetros 
# Si se pasa el ID en el body, trata de usarlo, si existe da error. 
# Si no se pasa el ID en el body, busca un id libre.
# permite usar ID o Nombres/Terminos para las relaciones.
# Si uno de los Id de relaciones no existe en la DB da un error
# y si se pasa una descripción, se la busca en su tabla y si no existe,
# se la da de alta en la tabla correspondiemnte.

### CASO CON ID !!!
POST {{baseUrl}}/contenido/
Content-Type: application/json

{
  "id": 101,
  "poster": "./posters/101.jpg",
  "titulo": "101 dalmatas",
  "categoria_id": "Película",
  "genero": [2, 12, 13],
  "busqueda": [3, 89, 99, 1124, 1125, 1126, 1127, 1128],
  "resumen": "Los Dálmatas son 101",
  "temporadas": 0,
  "duracion": 101,
  "reparto": [826, 827, 828, 829, 830, 831, 832, 833, 834],
  "trailer": "https://www.youtube.com/embed/G388UMkJIBE"
}   

### Get contenido por Id y relaciones full
GET {{baseUrl}}/contenido/101/full

### Get contenido por Id con array numérico en relaciones
GET {{baseUrl}}/contenido/101


### CASO SIN ID !!!
POST {{baseUrl}}/contenido/
Content-Type: application/json

{
  "id": 0,
  "poster": "./posters/10x.jpg",
  "titulo": "10x dalmatas",
  "categoria_id": "Película",
  "genero": [2, 12, 13, "Dálmatas"],
  "busqueda": [3, 89, 99, 1124, 1125, 1126, 1127, 1128, "10x dálmatas"],
  "resumen": "Los Dálmatas son cualquier ID",
  "temporadas": 0,
  "duracion": 101,
  "reparto": [826, 827, 828, 829, 830, 831, 832, 833, 834, "Perros Dálmatas"],
  "trailer": "https://www.youtube.com/embed/G388UMkJIBE"
}   

### Get contenido por Id y relaciones full
GET {{baseUrl}}/contenido/102/full


### Get contenido por Id con array numérico en relaciones
GET {{baseUrl}}/contenido/102


### Get contenido por Id con array numérico en relaciones
GET {{baseUrl}}/contenido/101

### Actualizar un contenido. COMPLETO !!!
####################################################################
# Resultados pos PUT
# "titulo": "101 dálmatas con manchas NEGRAS",
# "duracion": 102
# "resumen": "Los Dálmatas son 101 (PUT)",
# se quitó el id:13 en genero y agrega "Dálmatas" 
# se quitó el id:1128 en busqueda y agrega "101 dálmatas"
# se quitó el id:834 en reparto y agrega "Perros Dálmatas"
##################################################################
# Si el id de params no coincide con el elemento "id":, da un error!
PUT {{baseUrl}}/contenido/101
Content-Type: application/json

{
  "id": 101,
  "poster": "./posters/101.jpg",
  "titulo": "101 dálmatas con manchas NEGRAS",
  "categoria_id": "Película",
  "genero": [2, 12, "Dálmatas"],
  "busqueda": [3, 89, 99, 1124, 1125, 1126, 1127, "101 dálmatas"],
  "resumen": "Los Dálmatas son 101 (PUT)",
  "temporadas": 0,
  "duracion": 102,
  "reparto": [826, 827, 828, 829, 830, 831, 832, 833, "Perros Dálmatas"],
  "trailer": "https://www.youtube.com/embed/G388UMkJIBE"
}   

####################################################################
# NUEVO Contenido
####################################################################
#{
#  "id": 101,
#  "poster": "./posters/101.jpg",
#  "titulo": "101 dálmatas con manchas NEGRAS",
#  "categoria_id": 2,
#  "resumen": "Los Dálmatas son 101 (PUT)",
#  "temporadas": 0,
#  "duracion": 102,
#  "trailer": "https://www.youtube.com/embed/G388UMkJIBE",
#  "generoIds": [ 2, 12, 26 ],
#  "busquedaIds": [ 3, 89, 99, 1124, 1125, 1126, 1127, 1130 ],
#  "repartoIds": [ 826, 827, 828, 829, 830, 831, 832, 833, 842 ]
#}

### Get contenido por Id con array numérico en relaciones
GET {{baseUrl}}/contenido/101


##################################
# Actualizar un contenidos parcialmente
# se cambia "titulo": "101 dálmatas con manchas BLANCAS II"
# Hago que "id": sea obligatorio en el body y la URL  { id } = req.params
#  y además deben coincidir para que no de un error.
##################################
PATCH {{baseUrl}}/contenido/101
Content-Type: application/json

{
  "id": 101,
  "titulo": "101 dálmatas con manchas BLANCAS II",
  "resumen": "Los Dálmatas son 101 (PATCH)"
}

### Get contenido por Id con array numérico en relaciones
GET {{baseUrl}}/contenido/101

##################################
# Actualizar un contenidos parcialmente con datos vacios
# Da un error al mandar "titulo": "" sin datos, pero admite
# "poster": "" ya que además de ser opcional permite nulo y "". 
# Hago que "id": sea obligatorio en el body y la URL  { id } = req.params
#  y además deben coincidir para que no de un error.
##################################

### CASO CON ERRORES
PATCH {{baseUrl}}/contenido/101
Content-Type: application/json

{
  "id": 101,
  "poster": "",
  "titulo": ""
}

### CASO SIN ERRORES
PATCH {{baseUrl}}/contenido/101
Content-Type: application/json

{
  "id": 101,
  "poster": "",
  "titulo": "101 dálmatas con manchas BLANCAS II (2)",
  "resumen": "Los Dálmatas son 101 (PATCH) SIN ERRORES"
}

### Get contenido por Id con array numérico en relaciones
GET {{baseUrl}}/contenido/101

##################################
### Agrega solo nuevas relaciones a Contenido
# Categoríapasa a "Serie"
# "categoria_id": "Serie",  
# Generos
# Agrego {"id": 9, "nombre": "Suspenso" } por id
# Agrego {"id": 15, "nombre": "Tecnología"} por nombre
# Busquedas
# Agrego {"id": 4, "nombre": "Suspenso" } por nombre
# Agrego {"id": 5, "nombre": "Carl Weathers"} por id 
# Reparto
# Agrego {"id": 109, "nombre": "Aaron Paul" } por nombre
# Agrego {"id": 297, "nombre": "Adam Cozens"} por id 
##################################
PATCH {{baseUrl}}/contenido/agregar_relaciones/101             
Content-Type: application/json

{
  "id": 101,
  "categoria_id": 1,  
  "genero": [9, "Tecnología"],
  "busqueda": [5, "Suspenso"],
  "reparto": [297, "Aaron Paul"]
}   

####################################################################
# Resultados pos PATCH
##################################################################
# ANTES
#{
#  "id": 101,
#  "poster": "./posters/101.jpg",
#  "titulo": "101 dálmatas con manchas NEGRAS",
#  "categoria_id": 2,
#  "resumen": "Los Dálmatas son 101 (PUT)",
#  "temporadas": 0,
#  "duracion": 102,
#  "trailer": "https://www.youtube.com/embed/G388UMkJIBE",
#  "generoIds": [ 2, 12, 26 ],
#  "busquedaIds": [ 3, 89, 99, 1124, 1125, 1126, 1127, 1130 ],
#  "repartoIds": [ 826, 827, 828, 829, 830, 831, 832, 833, 842 ]

#}
# DESPUES
#{
#  "id": 101,
#  "poster": "./posters/101.jpg",
#  "titulo": "101 dálmatas con manchas NEGRAS",
#  "categoria_id": 1,  
#       --->  (PaSó a 1-Serie)
#  "resumen": "Los Dálmatas son 101 (PUT)",
#  "temporadas": 0,
#  "duracion": 102,
#  "trailer": "https://www.youtube.com/embed/G388UMkJIBE",
#  "generoIds": [ 2, 9, 12, 15, 26 ],
#       --->  Se suma (9 y 15)
#  "busquedaIds": [ 3, 4, 5, 89, 99, 1124, 1125, 1126, 1127, 1130 ],
#       --->  Se suma (5 y 4)
#  "repartoIds": [ 109, 297, 826, 827, 828, 829, 830, 831, 832, 833, 842 ]
#       --->  Se suma (109 y 297)
#}

### Get contenido por Id con array numérico en relaciones
GET {{baseUrl}}/contenido/101

##################################
### Eliminar relaciones a Contenido
# Generos
# Agrego {"id": 9, "nombre": "Suspenso" } por id
# Agrego {"id": 15, "nombre": "Tecnología"} por nombre
# Busquedas
# Agrego {"id": 4, "nombre": "Suspenso" } por nombre
# Agrego {"id": 5, "nombre": "Carl Weathers"} por id 
# Reparto
# Agrego {"id": 109, "nombre": "Aaron Paul" } por nombre
# Agrego {"id": 297, "nombre": "Adam Cozens"} por id 
##################################
PATCH {{baseUrl}}/contenido/eliminar_relaciones/101             
Content-Type: application/json

{
  "id": 101,
  "genero": [9, "Tecnología"],
  "busqueda": [5, "Suspenso"],
  "reparto": [297, "Aaron Paul"]
}   

####################################################################
# Resultados pos PATCH
##################################################################
# DEBERIA QUEDAR COMO ANTES 
#{
#  "id": 101,
#  "poster": "./posters/101.jpg",
#  "titulo": "101 dálmatas con manchas NEGRAS",
#  "categoria_id": 2,
#  "resumen": "Los Dálmatas son 101 (PUT)",
#  "temporadas": 0,
#  "duracion": 102,
#  "trailer": "https://www.youtube.com/embed/G388UMkJIBE",
#  "generoIds": [ 2, 12, 26 ],
#       --->  Se quita (9 y 15)
#  "busquedaIds": [ 3, 89, 99, 1124, 1125, 1126, 1127, 1130 ],
#       --->  Se quita (4 y 5)
#  "repartoIds": [ 826, 827, 828, 829, 830, 831, 832, 833, 842 ]
#       --->  Se quita (109 y 297)


### Get contenido por Id con array numérico en relaciones
GET {{baseUrl}}/contenido/101





################################
### Delete contenido por Id
################################
#  Delete !!!!!!!! OJO!
################################
DELETE {{baseUrl}}/contenido/101
################################
DELETE {{baseUrl}}/contenido/102
################################
DELETE {{baseUrl}}/contenido/103

### Get contenido por Id con array numérico en relaciones
GET {{baseUrl}}/contenido/101
### Get contenido por Id con array numérico en relaciones
GET {{baseUrl}}/contenido/102
### Get contenido por Id con array numérico en relaciones
GET {{baseUrl}}/contenido/103





################################
##  GENEROS
################################

### Get de todos los generos
GET {{baseUrl}}/generos

### Get generos por Id
GET {{baseUrl}}/generos/1
### Get generos por Id
GET {{baseUrl}}/generos/2
### Get generos por Id
GET {{baseUrl}}/generos/399999

### Crear un genero
POST {{baseUrl}}/generos
Content-Type: application/json

{
  "nombre": "comi-trágico"
}

### Get generos por Id
GET {{baseUrl}}/generos/27

### Get generos por Id
GET {{baseUrl}}/generos/24

### Get generos por Id
GET {{baseUrl}}/generos/25

### Get generos por Id
GET {{baseUrl}}/generos/26


### Actualizar un genero totalmente 
PUT {{baseUrl}}/generos/27
Content-Type: application/json

{
  "nombre": "comi-trágico-griego"
}

### Delete generos por Id
# Si el genero está usado en la tabla contenido_generos, da un error!
DELETE {{baseUrl}}/generos/27







################################
##  CATEGORIAS
################################


### Get de todos las categorias
GET {{baseUrl}}/categorias

### Get categorias por Id
GET {{baseUrl}}/categorias/2

### Get categorias por Id
GET {{baseUrl}}/categorias/1

### Get categorias por Id
GET {{baseUrl}}/categorias/3

### Crear una categorias
POST {{baseUrl}}/categorias
Content-Type: application/json

{
  "nombre": "Documental"
}

### Actualizar una categorias totalmente 
PUT {{baseUrl}}/categorias/3
Content-Type: application/json

{
  "nombre": "Documental-serie-galaxia"
}

### Actualizar una categorias parcialmente
PATCH {{baseUrl}}/categorias/3
Content-Type: application/json

{
  "nombre": "Documental-serie-galaxia2"
}

### Actualizar una categorias parcialmente con datos invalidos
PATCH {{baseUrl}}/categorias/3
Content-Type: application/json

{
  "nombres": "ssss"
}

### Actualizar una categorias parcialmente con datos vacios
PATCH {{baseUrl}}/categorias/3
Content-Type: application/json

{
  "nombre": ""
}

### DELETE categorias por Id
DELETE {{baseUrl}}/categorias/3
### DELETE categorias por Id (No permitido)
DELETE {{baseUrl}}/categorias/1







################################
##  ACTORES
################################

### Get de todos los actores
GET {{baseUrl}}/actores

### Get actor por Id
GET {{baseUrl}}/actores/1
### Get actor por Id
GET {{baseUrl}}/actores/109


### Crear un actor
POST {{baseUrl}}/actores
Content-Type: application/json

{
  "nombre": "Gustavo Torrente"
}

### Actualizar un actor totalmente 
PUT {{baseUrl}}/actores/841
Content-Type: application/json

{
  "nombre": "Gustavo Torrente Nuñez"
}

### Get actor por Id
GET {{baseUrl}}/actores/841

### Actualizar un actor parcialmente
PATCH {{baseUrl}}/actores/841
Content-Type: application/json

{
  "nombre": "Gustavo Torrente Nuñez Quijada"
}

### Actualizar un actor parcialmente con datos invalidos
PATCH {{baseUrl}}/actores/840
Content-Type: application/json

{
  "nombres": "ssss"
}

### Actualizar un actor parcialmente con datos vacios
PATCH {{baseUrl}}/actores/840
Content-Type: application/json

{
  "nombre": ""
}


### Get actor por Id
GET {{baseUrl}}/actores/109

### DELEte actores por Id (No permitido)
# Con detección de error "SequelizeForeignKeyConstraintError"
# 
DELETE {{baseUrl}}/actores/109



################################
##  GENEROS
################################

### Get de todos los generos
GET {{baseUrl}}/generos

### Get genero por Id
GET {{baseUrl}}/generos/24



### Crear un genero
POST {{baseUrl}}/generos
Content-Type: application/json

{
  "nombre": "Tragedia"
}

### Actualizar un genero totalmente 
PUT {{baseUrl}}/generos/20
Content-Type: application/json

{
  "nombre": "Tragedia Griega"
}

### Actualizar un genero parcialmente
PATCH {{baseUrl}}/generos/20
Content-Type: application/json

{
  "nombre": "Tragedia Griega"
}

### Actualizar un genero parcialmente con datos vacios
PATCH {{baseUrl}}/generos/840
Content-Type: application/json

{
  "nombre": ""
}
